### ISSUE TITLE
Default Pallete for plotGE and plotSpots are hard to see

### ISSUE THREAD

**Issue by boyiguo1** [lmweber/ggspavis#10]
Is it possible to change the default to something that See well. Currently, I am using black and white. However, the white doesn't see well with the white background. Is it possible to add outline to the spots to tell if there is a spot.
 
 Relevantly, if we want to plot a multi-dimensional data set, e.g. both expression and categorical variable, is it possible to use outline of the spots to show the additional dimension of the data, for example, circle vs hexagon.

**Comment by lmweber** [comment]
Closing this issue since I believe this is now partly addressed by the recent updates to the plotting functions / default palettes (see [utils.R](https://github.com/lmweber/ggspavis/blob/devel/R/utils.R)), as well as your [escheR](https://bioconductor.org/packages/escheR) package. Thanks!
