### ISSUE TITLE
weird rotation for spots and underlying image

### ISSUE THREAD

**Issue by giovp** [lmweber/ggspavis#4]
I get this weird rotation between image and spots

<img width="473" alt="image" src="https://user-images.githubusercontent.com/25887487/165314098-23c19812-d62b-49bc-961d-632cda13748c.png">

this is how I create the Spatial Experiment object

```r
path_adata <- "/data/day3_spatial_transcriptomics"
ad <- readH5AD(paste0(path_adata,"/V10F24-105_A1_destvi.h5ad"))

coords <- as.matrix(reducedDim(ad, "spatial"))
colnames(coords) = c("x","y")
spe <- SpatialExperiment(
    assay = assay(ad,"X"), 
    colData = ad@colData, 
    spatialCoords = coords,
)
spe[["sample_id"]] <- "V10F24-105_A1"

path_img <- "/home/rstudio/adv_singlecell_2022/day3_spatial_transcriptomics/V10F24-105_A1.png"
spe <- addImg(spe, 
    sample_id = "V10F24-105_A1", 
    image_id = "V10F24-105_A1",
    imageSource = path_img, 
    scaleFactor = 0.04155585, 
    load = TRUE)

```

data is converted with zellkonverter (will ping you over at that repo for start thinking about proper conversion).

The image is also from anndata but it's the same as the spaceranger output. I can provide data easily if needed.

**Comment by giovp** [comment]
I think the error was in the data storage and didn't ahve to do with ggpsavis. Can be closed

**Comment by lmweber** [comment]
Ok, thank you! Apologies, I hadn't replied to this issue yet.
